### ISSUE TITLE
Freight doesn't render on Safari browsers (MacOS, iPad)

### ISSUE THREAD

**Issue by GreyAdorim** [macniel/sc-manifest#2]
- Major: Freight tab not usable, no images render
- Minor: Text is clipped on the qty selection
- Screenshot attached:
<img width="1750" alt="SC_Manifest" src="https://user-images.githubusercontent.com/95876674/145446719-2f4fc898-6fd1-4577-bd81-a2f5172ae691.png">

**Comment by macniel** [comment]
Looks like Safari doesn't like having SVG as a background-image.

**Comment by macniel** [comment]
Commodities are now displayed with icon on iPad. 
As the numberpad was redesigned, the clipping error also was fixed.

thanks again for reporting.
